# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 654)
        font = QtGui.QFont()
        font.setFamily("Microsoft PhagsPa")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(0, 170, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -30, 561, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color:#cc66ff")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 30, 561, 101))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #ffffcc\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 60, 31, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("blood_drop_icon-icons.com_76228.png"))
        self.label_2.setObjectName("label_2")
        self.item_eritr = QtWidgets.QLineEdit(self.centralwidget)
        self.item_eritr.setGeometry(QtCore.QRect(10, 90, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_eritr.setFont(font)
        self.item_eritr.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_eritr.setText("")
        self.item_eritr.setAlignment(QtCore.Qt.AlignCenter)
        self.item_eritr.setObjectName("item_eritr")
        self.item_hemogl_m = QtWidgets.QLineEdit(self.centralwidget)
        self.item_hemogl_m.setGeometry(QtCore.QRect(10, 170, 231, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_hemogl_m.setFont(font)
        self.item_hemogl_m.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_hemogl_m.setText("")
        self.item_hemogl_m.setAlignment(QtCore.Qt.AlignCenter)
        self.item_hemogl_m.setObjectName("item_hemogl_m")
        self.item_cvet_pokaz = QtWidgets.QLineEdit(self.centralwidget)
        self.item_cvet_pokaz.setGeometry(QtCore.QRect(170, 90, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_cvet_pokaz.setFont(font)
        self.item_cvet_pokaz.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_cvet_pokaz.setText("")
        self.item_cvet_pokaz.setAlignment(QtCore.Qt.AlignCenter)
        self.item_cvet_pokaz.setObjectName("item_cvet_pokaz")
        self.item_leyk = QtWidgets.QLineEdit(self.centralwidget)
        self.item_leyk.setGeometry(QtCore.QRect(10, 380, 461, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_leyk.setFont(font)
        self.item_leyk.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_leyk.setText("")
        self.item_leyk.setAlignment(QtCore.Qt.AlignCenter)
        self.item_leyk.setObjectName("item_leyk")
        self.item_trombocit = QtWidgets.QLineEdit(self.centralwidget)
        self.item_trombocit.setGeometry(QtCore.QRect(330, 90, 141, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_trombocit.setFont(font)
        self.item_trombocit.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_trombocit.setText("")
        self.item_trombocit.setAlignment(QtCore.Qt.AlignCenter)
        self.item_trombocit.setObjectName("item_trombocit")
        self.item_hemogl_women = QtWidgets.QLineEdit(self.centralwidget)
        self.item_hemogl_women.setGeometry(QtCore.QRect(250, 170, 221, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_hemogl_women.setFont(font)
        self.item_hemogl_women.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_hemogl_women.setText("")
        self.item_hemogl_women.setAlignment(QtCore.Qt.AlignCenter)
        self.item_hemogl_women.setObjectName("item_hemogl_women")
        self.item_reticulociti = QtWidgets.QLineEdit(self.centralwidget)
        self.item_reticulociti.setGeometry(QtCore.QRect(10, 240, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_reticulociti.setFont(font)
        self.item_reticulociti.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_reticulociti.setText("")
        self.item_reticulociti.setAlignment(QtCore.Qt.AlignCenter)
        self.item_reticulociti.setObjectName("item_reticulociti")
        self.item_hem_m = QtWidgets.QLineEdit(self.centralwidget)
        self.item_hem_m.setGeometry(QtCore.QRect(170, 240, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_hem_m.setFont(font)
        self.item_hem_m.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_hem_m.setText("")
        self.item_hem_m.setAlignment(QtCore.Qt.AlignCenter)
        self.item_hem_m.setObjectName("item_hem_m")
        self.item_hem_w = QtWidgets.QLineEdit(self.centralwidget)
        self.item_hem_w.setGeometry(QtCore.QRect(330, 240, 141, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_hem_w.setFont(font)
        self.item_hem_w.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_hem_w.setText("")
        self.item_hem_w.setAlignment(QtCore.Qt.AlignCenter)
        self.item_hem_w.setObjectName("item_hem_w")
        self.item_soe_m = QtWidgets.QLineEdit(self.centralwidget)
        self.item_soe_m.setGeometry(QtCore.QRect(10, 310, 241, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_soe_m.setFont(font)
        self.item_soe_m.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_soe_m.setText("")
        self.item_soe_m.setAlignment(QtCore.Qt.AlignCenter)
        self.item_soe_m.setObjectName("item_soe_m")
        self.item_soe_w = QtWidgets.QLineEdit(self.centralwidget)
        self.item_soe_w.setGeometry(QtCore.QRect(260, 310, 211, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_soe_w.setFont(font)
        self.item_soe_w.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_soe_w.setText("")
        self.item_soe_w.setAlignment(QtCore.Qt.AlignCenter)
        self.item_soe_w.setObjectName("item_soe_w")
        self.item_neitr_segm = QtWidgets.QLineEdit(self.centralwidget)
        self.item_neitr_segm.setGeometry(QtCore.QRect(10, 450, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_neitr_segm.setFont(font)
        self.item_neitr_segm.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_neitr_segm.setText("")
        self.item_neitr_segm.setAlignment(QtCore.Qt.AlignCenter)
        self.item_neitr_segm.setObjectName("item_neitr_segm")
        self.item_neitr_palochk = QtWidgets.QLineEdit(self.centralwidget)
        self.item_neitr_palochk.setGeometry(QtCore.QRect(170, 450, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_neitr_palochk.setFont(font)
        self.item_neitr_palochk.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_neitr_palochk.setText("")
        self.item_neitr_palochk.setAlignment(QtCore.Qt.AlignCenter)
        self.item_neitr_palochk.setObjectName("item_neitr_palochk")
        self.item_bazofili = QtWidgets.QLineEdit(self.centralwidget)
        self.item_bazofili.setGeometry(QtCore.QRect(330, 450, 141, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_bazofili.setFont(font)
        self.item_bazofili.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_bazofili.setText("")
        self.item_bazofili.setAlignment(QtCore.Qt.AlignCenter)
        self.item_bazofili.setObjectName("item_bazofili")
        self.item_eozinofili = QtWidgets.QLineEdit(self.centralwidget)
        self.item_eozinofili.setGeometry(QtCore.QRect(10, 520, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_eozinofili.setFont(font)
        self.item_eozinofili.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_eozinofili.setText("")
        self.item_eozinofili.setAlignment(QtCore.Qt.AlignCenter)
        self.item_eozinofili.setObjectName("item_eozinofili")
        self.item_monocit = QtWidgets.QLineEdit(self.centralwidget)
        self.item_monocit.setGeometry(QtCore.QRect(170, 520, 151, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_monocit.setFont(font)
        self.item_monocit.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_monocit.setText("")
        self.item_monocit.setAlignment(QtCore.Qt.AlignCenter)
        self.item_monocit.setObjectName("item_monocit")
        self.item_limfociti = QtWidgets.QLineEdit(self.centralwidget)
        self.item_limfociti.setGeometry(QtCore.QRect(330, 520, 141, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.item_limfociti.setFont(font)
        self.item_limfociti.setStyleSheet("background-color:#99ccff;\n"
"border : 2px solid #0000ff;\n"
"border-radius: 30;\n"
"color: black")
        self.item_limfociti.setText("")
        self.item_limfociti.setAlignment(QtCore.Qt.AlignCenter)
        self.item_limfociti.setObjectName("item_limfociti")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 590, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:white;\n"
"background-color:#3333ff;\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Общий анализ крови</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Расшифровать анализ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
